# Generated by Django 5.0.3 on 2024-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
